language: node_js
node_js:
  - 10
  - 12
  - 14
install:
  - npm install
script:  
  - npm run ci
after_script: 
  - npm i coveralls
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
